baseURL = "/"
languageCode = "en-us"
title = "Dewald de Jager"

theme = "coder"

[params]
    author = "Dewald de Jager"
    info = "Full Stack Software Engineer"
    description = "The personal website and blog of Dewald de Jager."
    avatarurl = "/images/avatar.jpg"
    custom_css = ["/css/style.css"]
    math = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/DewaldDeJager/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/dewaldjdejager/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/DewaldDeJager/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/blog/"
[[menu.main]]
    name = "Contact"
    weight = 5
url = "/contact/"